name: daily_music
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icon
  line_awesome_flutter: ^2.0.0
  cupertino_icons: ^1.0.2

  # StateManagement & DI
  flutter_riverpod: ^2.3.7
  equatable: ^2.0.3
  get_it: ^7.2.0

  # Local Storage
  sqflite: ^2.0.2+1
  connectivity_plus: ^4.0.2
  shared_preferences: ^2.0.15
  lottie: ^1.4.1
  flutter_dotenv: ^5.0.2
  google_mobile_ads: ^3.0.0
  permission_handler: ^10.0.0

  # FireBase
  google_sign_in: ^5.3.1
  firebase_core: ^2.17.0
  firebase_messaging: ^14.7.4
  firebase_analytics: ^10.6.4
  cloud_firestore: ^4.13.0

  # Youtube Download
  youtube_explode_dart: ^2.0.2

  # Audio
  just_audio: ^0.9.24
  ffmpeg_kit_flutter_audio: 5.1.0-LTS
  audio_service: ^0.18.12

  # Apis
  dio: ^5.3.2

  # Routing
  go_router: ^11.1.3

  # Utils
  flutter_local_notifications: ^11.0.0
  flutter_svg: ^1.1.5
  image_picker: ^0.8.5+3
  google_fonts: ^5.1.0
  fpdart: ^1.1.0
  path_provider: ^2.0.11
  share_plus: ^4.0.7
  path_to_regexp: ^0.4.0
  flutter_screenutil: ^5.9.0

  # Widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^2.0.1
  riverpod_lint: ^2.0.1
  custom_lint:

  # Code gen
  build_runner: ^2.2.0
  riverpod_generator: ^2.2.6
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  riverpod_annotation: ^2.2.0

flutter_native_splash:
  color: "#ffffff"
  image: images/unnamed.png
dependency_overrides:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - .env

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
