name: daily_music
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icon
  cupertino_icons: ^1.0.6

  # StateManagement & DI
  flutter_riverpod: ^2.3.7
  equatable: ^2.0.3
  get_it: ^7.6.4

  # Local Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.2.2

  # FireBase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  cloud_firestore: ^4.13.6

  # Youtube Download
  youtube_explode_dart: ^2.1.0

  # Audio
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  ffmpeg_kit_flutter_audio: 5.1.0-LTS

  # Apis
  dio: ^5.4.1

  # Routing
  go_router: ^13.2.0

  # Utils
  flutter_local_notifications: ^16.3.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  fpdart: ^1.1.0
  path_provider: ^2.0.11
  share_plus: ^7.2.2
  path_to_regexp: ^0.4.0
  connectivity_plus: ^5.0.2
  lottie: ^3.0.0
  flutter_dotenv: ^5.0.2
  google_mobile_ads: ^4.0.0
  permission_handler: ^11.3.0
  file_picker: ^6.1.1
  audio_video_progress_bar: ^2.0.1
  json_annotation: ^4.8.1
  go_router_builder: ^2.4.1
  logger: ^2.0.2+1
  modal_bottom_sheet: ^3.0.0-pre
  animations: ^2.0.11

  # Widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.1.0
  custom_lint:

  # Code gen
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  riverpod_annotation: ^2.3.4

flutter_native_splash:
  color: "#ffffff"
  image: images/unnamed.png
dependency_overrides:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - .env

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
