// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE8Ru0eDDx68Cr3In01jHQpnL1bJjKE9Q',
    appId: '1:162625826936:web:b67c1e3b5a4bec8f41bd8d',
    messagingSenderId: '162625826936',
    projectId: 'daily-music-a3d6e',
    authDomain: 'daily-music-a3d6e.firebaseapp.com',
    storageBucket: 'daily-music-a3d6e.appspot.com',
    measurementId: 'G-EPW3W9KWQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3mI_2WLL7hON0QxdI3NuPnSzgHT-C4fg',
    appId: '1:162625826936:android:f574ba74d419d6f141bd8d',
    messagingSenderId: '162625826936',
    projectId: 'daily-music-a3d6e',
    storageBucket: 'daily-music-a3d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwxub6cyHKymm5jFT6CxBd65xi91MptGQ',
    appId: '1:162625826936:ios:976de6424d7d6fd341bd8d',
    messagingSenderId: '162625826936',
    projectId: 'daily-music-a3d6e',
    storageBucket: 'daily-music-a3d6e.appspot.com',
    iosClientId: '162625826936-3k4mf967u42r6jpvm0e91km9qk83qf13.apps.googleusercontent.com',
    iosBundleId: 'com.park.daliyMusic',
  );
}
