// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB76gKL_W-RdfC7B1YPtg4CIv_IlxxvGxU',
    appId: '1:196115385458:web:72b8db6c0cb61ab7f2c6eb',
    messagingSenderId: '196115385458',
    projectId: 'dailymusic-1de6d',
    authDomain: 'dailymusic-1de6d.firebaseapp.com',
    storageBucket: 'dailymusic-1de6d.appspot.com',
    measurementId: 'G-6G9S0DYWE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCySqS9U5-bCQwUBFBpt8aitw4buJQM9Ho',
    appId: '1:196115385458:android:1b00b8b266ca1236f2c6eb',
    messagingSenderId: '196115385458',
    projectId: 'dailymusic-1de6d',
    storageBucket: 'dailymusic-1de6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY0z-8elpZoyQElX7nXBrkgI0AO6AiPDc',
    appId: '1:196115385458:ios:1879d49511423cb4f2c6eb',
    messagingSenderId: '196115385458',
    projectId: 'dailymusic-1de6d',
    storageBucket: 'dailymusic-1de6d.appspot.com',
    iosClientId:
        '196115385458-h94tllpa1f5n32k228fpp0si7qq7i4ta.apps.googleusercontent.com',
    iosBundleId: 'com.example.daliyMusic',
  );
}
